name: first
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
#flutter pub run build_runner build --delete-conflicting-outputs


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations :
    sdk: flutter
  sizer: ^2.0.15
  get: ^4.6.5
  dropdown_button2: ^2.0.0
  pinput: ^2.2.16
  searchbar_animation: ^0.0.4
  bot_toast: ^4.0.3
  text_scroll: ^0.1.1
  rating_dialog: ^2.0.0
  google_nav_bar: ^5.0.4
  flutter_svg : ^2.0.4
  flutter_staggered_grid_view: ^0.4.1
  get_storage: ^2.0.2
  dio: ^5.0.0
  device_info_plus: ^7.0.0
  font_awesome_flutter: ^10.2.0
  location: ^4.1.1
  url_launcher: ^6.1.4
  cached_network_svg_image: ^0.0.7
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.2.8
  flutter_typeahead: ^4.6.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0  
  build_runner: ^2.4.6


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/images_svg/
    - assets/lang/



#  fonts:
#    - family: Amiri
#      fonts:
#       - asset: assets/fonts/amiri/



