const Map<String, String> ar = {
  //RegisterView
  'Sing Up': 'إنشاء حساب',
  'username': 'اسم المستخدم',
  'Field is required': "اسم المستخدم مطلوب",
  'email': 'البريد إلكتروني',
  'please enter your email':"عنوان البريد إلكتروني مطلوب",
  'Enter valid email address':'ادخل عنوان بريد إلكتروني صالح',
  'password': 'كلمة المرور',
  "Not Found Areas":"لايوجد مناطق",
   "Not found categories":'لايوجد تصنيفات',
      "Not found places":'لايوجد أماكن',
    "The places of top rating":" الأماكن الأعلى تقييما حسب المستخدمين",
   'Search in': "البحث في",
  'Please enter password': 'كلمة المرور مطلوب',
  'Search Region ...':"البحث عن منطقة",
  'Enter valid password':"كلمة المرور ضعيفة",
  'confirm password': 'تأكيد كلمة المرور',
  'plz confirm password': 'يجب تأكيد كلمة المرور',
  "not match":"كلمة المرور غير مطابقة",
  "Password must be atleast 8 characters long":"يجب أن تكون كلمة المرور أكثر من 8 محارف",
  'phone number': 'رقم الهاتف',
  'Please enter valid mobile number':"رقم هاتف غير صالح",
  "phone number is required":"رقم الهاتف مطلوب",
  'select area': 'اختر المنطقة',
   "select region is required":"يجب اختيار المنطقة",
  'select street': 'اختر الشارع',
  "select street is required":"يجب اختيارالشارع",
  'search area': 'البحث عن منطقة',
  'search street': 'البحث عن شارغ',
  'Do you have a already account?': 'هل تملك حساب مسبقا؟',
  "select gender is required":"يجب تحديد الجنس",
  "LogIn": 'تسجيل دخول',
  "male": "ذكر",
  "female": "أنثى",
  'Do not Have account?': 'إذا كنت لا تملك حساب؟',
  "Register": 'إنشاء حساب',

  'login': 'تسجيل دخول',
  "Success login":"تم تسجيل الدخول بنجاح",
  "Email is invalid":"عنوان البريد الإلكتروني غير متاح",
  'hello': 'مرحبا',
  // 'username': 'اذهب للشاشة التالية',
  "notification": "الاشعار",
  "Try again":"محاولة ثانية",
  //homeview
  'Home': 'الرئيسية',
  'Favorites': 'المفضلة',
  'CategoriesNav': 'التصنيفات',
  'ProfileNav': 'الملف الشخصي',
  "Your Comments":"تعليقاتك على الأماكن",

  //HomeDetailsView
  'Guide': 'دليل حلب الشامل',
  'Ads': 'الإعلانات',
  'CategoriesMain': 'التصنيفات',
  'The nearly to me': 'الأقرب لي',
  'Search HomeDetailsView ...': 'البحث عن تصنيف...',
  //  'Search Category ...':'البحث عن تصنيف ...',
  //Profile
  'Profile': 'الملف الشخصي',
  'nameuser': 'ضياء كنده',
  'emailProfile': 'Profile@gmail.com',
  'favorites': 'المفضلة',
  'comment': 'تعليقاتك',
  'settings': 'اللغة',
  'logout': 'تسجيل الخروج',
  "No favorite":"لا يوجد مفضلة",
  //CategoryView
  'Categories': 'التصنيفات',
  'NameCategories': 'اسم التصنيف',
  //CategoryItemview
  'CategoryItem': 'CategoryItem',
  //commentview
  // 'Your Comments': 'تعليقك',
  "content required":"التعليق مطلوب",
  "Changing your password":"تغيير كلمة المرور",
  'Please enter old password':'ادخل كلمة المرور القديمة',
    "New password":"كلمة السر الجديدة",
  //Favorite
  'Favorite': 'المفضلة',
  'Places': 'المكان',
 "Services": 'الخدمة',
  //PlaceService
  'Description': 'الوصف',
  "Inquire about the product": "للاستفسار عن المنتج",
  "View the information card": "عرض بطاقة المعلومات",
  //PlaceDetailsView
  "Shose Chic": 'شوز شيك',
  '0937 768 105':'0937 768 105',
  "Comments and Ratings":'التعليقات والتقييمات',
  'Show more':'عرض المزيد',
   "Add Comment and Rating":'إضافة تعليق وتقييم',
   // 'places': 'places',
  // 'ervices': 'خدمات',

  "All Comments":"كل التعليقات" ,
  "Add Comment For Place":"اضف تعليق وتقييم",
  "Submit":"إرسال",
  "Comment and Ratting":"تعليقك",

  'Search Category ...':"البحث عن تصنيف",
  "Show all":"عرض الكل",
  "Update":"تحديث",
  "Delete":"حذف",
  "Cancel":"إغلاق",
  "Search in ":"البحث في",
  'Search Place ...':"البحث عن مكان",
   "?You haven't received the message yet":" ?لم تصلك رسالة",
   "Send again":"إعادة الإرسال",
  "search place":"ابحث عن مكان",
  "Create new password":"إنشاء كلمة سر جديدة",
  "Areas":"المناطق",
   "Save":"حفظ",
   "Edite Profile":"تعديل الملف الشخصي",
   "Change Password":'تغيير كلمة المرور',
   "Did you forget your password":" نسيت كلمة المرور",
    // "No place in this name to show":"ابحث عن مكان",
    "No":"رجوع",
    "Yes":"تأكيد",
    "Are You Sure?":"هل تريد تسجيل الخروج من التطبيق؟",
    "Verification":"تأكيد",
  "open":"تشغيل",
  "ORIGIN":"موقعك",
  "DEST":"الوجهة",
  "The selected email is invalid":"البريد الإلكتروني المحدد غير صالح",
  "Data is invalid":"البيانات غير صالحة",
  "Success Register":"تم إنشاء الحساب بنجاح"
};
