const Map<String, String> en = {
  //RegisterView
  'Sing Up': 'Sing Up',
  'username': 'username',
  'Field is required': 'Field is required',
  'email': 'email',
    'please enter your email':  'please enter your email',
    'Enter valid email address':'Enter valid email address',
  'password': 'password',
  'Please enter password': 'Please enter password',
  'Enter valid password':'Enter valid password',
  'confirm password': 'confirm password',
  'plz confirm password': 'plz confirm password',
  "not match":"not match password",
  "Password must be atleast 8 characters long":"Password must be atleast 8 characters long",
  'phone number': 'phone number',
  "phone number is required":"phone number is required",
  'Please enter valid mobile number':'plz enter valid mobile number',
  'select area': 'select area',
   "select region is required": "select region is required",
   "select street is required":"select street is required",
  'search street': 'search street',
  'select street': 'select street',
  'search area': 'search area',
  "select gender is required":"select gender is required",
  'Do you have a already account?': 'Do you have a already account?',
  "Log In": "Log In",
  "male": "male",
  "female": "female",
  'Do not Have account?': 'Do not Have account?',
  "Register": 'Register',
   "The places of top rating":"The places of top rating",
  'login': 'login',
  'hello': 'Hello',
  "Success login":"Success login",
  "Email is invalid":"Email is invalid",
  // 'username': 'Go to Screen',
  "notification": "Notification",
  //homeview
  'Home': 'Home',
  'Favorites': 'Favorites',
  'CategoriesNav': 'Categories',
  'ProfileNav': 'ProfileNav',

  //HomeDetailsView
  'Guide': 'Guide',
  'Ads': 'Ads',
  'CategoriesMain': 'Categories',
  'The nearly to me': 'The nearly to me',
  'Search HomeDetailsView ...': 'Search Category ...',
  // 'Search Category ...':'Search Category ...',

  //Profile
  'Profile': 'Profile',
  'nameuser': 'Dia Kinda',
  'emailProfile': 'Profile@gmail.com',
  'favorites': 'Favorites',
  'comment': 'Your Comments',
  'settings': 'Language',
  'logout': 'Log out',

  //CategoryView
  'Categories': 'Categories',
  'NameCategories': 'NameCategories',

  //CategoryItemview
  'CategoryItem': 'CategoryItem',
  //commentview
  'Your Comments': 'Your Comments',
  //Favorite
  'Favorite': 'Favorite',
  'Places': 'places',
  "Services": 'Services',
  //PlaceService
  'Description': 'Description',
  "Inquire about the product": "Inquire about the product",
  "View the information card": "View the information card",
  // 'places': 'places',
  // 'services': 'services',

  //PlaceDetailsView
  "Shose Chic": "Shose Chic",
  '0937 768 105': '0937 768 105',
  "Comments and Ratings": "Comments and Ratings",
  // 'places': 'places',
  'services': 'services',
  'Show more':'Show more',
   "Add Comment and Rating": "Add Comment and Rating",

   "All Comments":"All Comments",

   "Add Comment For Place":"Comment and Ratting ",
   "Submit":"submit",
   "Comment and Ratting":"What are your comment",
   "Create new password":"Create new password",
'Search Region ...':'Search Region ...',
"Search in":"Search in",
"Not Found Areas":"Not Found Areas",
 "Not found categories": "Not found categories",
   "Not found places":   "Not found places",
   'Search Category ...':'Search Category ...',
   "Show all":"Show all",
   "Update":"Update",
   "Delete":"Delete",
   "Cancel":"Cancel",
   'Search Place ...':'Search Place ...',
   "No place in this name to show":"No place in this name to show",
   "search place":"search place",
   "Areas":"Areas",
   "Save": "Save",
   "Edite Profile":"Edite Profile",
   "Change Password":"Change Password",
   "Did you forget your password":"Did you forget your password",
   "No":"No",
   "Yes":"Yes",
    "Try again": "Try again",
   "Send again":"Send again",
   "Search in ":"Search in ",
    "?You haven't received the message yet": "?You haven't received the message yet",
   "New password":  "New password",
   "Are You Sure?":"Are You Sure?",
   "Verification":"Verification",
   "content required":"content required",
   "Changing your password":"Changing your password",
   'Please enter old password':'Please enter old password',
   "No favorite":"No favorite",
  "open":"open",
  "ORIGIN":"ORIGIN",
  "DEST":"DEST",
  "The selected email is invalid":"The selected email is invalid",
  "Data is invalid":"Data is invalid",
  "Success Register":"Success Register"
  };
